# Generated by Django 5.2.8 on 2026-04-07 22:09

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaExercicio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Exercício',
                'verbose_name_plural': 'Categorias de Exercícios',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('telefone_comercial', models.CharField(blank=True, max_length=15)),
                ('data_nascimento', models.DateField()),
                ('data_matricula', models.DateField()),
                ('plano', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProcedimento',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('habilita_exercicios', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Procedimento',
                'verbose_name_plural': 'Tipos de Procedimento',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExercicioCatalogo',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('max_sessoes_consecutivas', models.PositiveIntegerField(default=2)),
                ('sessoes_ate_cooldown', models.PositiveIntegerField(default=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicios', to='forms.categoriaexercicio')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='forms.paciente')),
                ('tipo_procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='forms.tipoprocedimento')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FichaExercicios',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_exercicios', to='forms.paciente')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_exercicios', to='forms.procedimento')),
            ],
            options={
                'verbose_name': 'Ficha de Exercícios',
                'verbose_name_plural': 'Fichas de Exercícios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('faltou', 'Faltou'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('assinatura_confirmada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='forms.procedimento')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['data_hora'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='forms.paciente')),
                ('tipo_avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes', to='forms.tipoavaliacao')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_hora'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedimentoExercicio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimento_exercicios', to='forms.exerciciocatalogo')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimento_exercicios', to='forms.procedimento')),
            ],
            options={
                'verbose_name': 'Exercício do Procedimento',
                'verbose_name_plural': 'Exercícios do Procedimento',
                'ordering': ['ordem', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('procedimento', 'exercicio'), name='unique_active_exercicio_por_procedimento')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SessaoExercicio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessao_exercicios', to='forms.exerciciocatalogo')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_exercicios', to='forms.sessao')),
            ],
            options={
                'verbose_name': 'Exercício da Sessão',
                'verbose_name_plural': 'Exercícios da Sessão',
                'ordering': ['ordem', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sessao', 'exercicio'), name='unique_active_exercicio_por_sessao')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
