# Generated by Django 4.2.7 on 2026-02-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamneseacupuntura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_acupuntura', to='forms.fichainscricao'),
        ),
        migrations.AddField(
            model_name='anamnesegeral',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_geral', to='forms.fichainscricao'),
        ),
        migrations.AddField(
            model_name='fichadrenagem',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_drenagem', to='forms.fichainscricao'),
        ),
        migrations.AddField(
            model_name='fichaexercicios',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_exercicios', to='forms.fichainscricao'),
        ),
    ]
