# Generated by Django 4.2.7 on 2026-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamneseacupuntura',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anamnese - Acupuntura', 'verbose_name_plural': 'Anamneses - Acupuntura'},
        ),
        migrations.AlterModelOptions(
            name='anamnesegeral',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anamnese Geral', 'verbose_name_plural': 'Anamneses Gerais'},
        ),
        migrations.AlterModelOptions(
            name='fichadrenagem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ficha de Avaliação - Drenagem Linfática', 'verbose_name_plural': 'Fichas de Avaliação - Drenagem Linfática'},
        ),
        migrations.AlterModelOptions(
            name='fichaexercicios',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ficha de Exercícios', 'verbose_name_plural': 'Fichas de Exercícios'},
        ),
        migrations.AlterModelOptions(
            name='fichainscricao',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ficha de Inscrição', 'verbose_name_plural': 'Fichas de Inscrição'},
        ),
        migrations.RenameField(
            model_name='anamneseacupuntura',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='anamneseacupuntura',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='anamnesegeral',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='anamnesegeral',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='fichadrenagem',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='fichadrenagem',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='fichaexercicios',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='fichaexercicios',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='fichainscricao',
            old_name='criado_em',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='fichainscricao',
            old_name='atualizado_em',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='anamneseacupuntura',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='anamnesegeral',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fichadrenagem',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='fichaexercicios',
            name='dia',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
