# Generated by Django 4.2.7 on 2026-03-06 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forms', '0006_convert_date_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnesegeral',
            name='dor',
        ),
        migrations.RemoveField(
            model_name='anamnesegeral',
            name='medicamentos_quais',
        ),
        migrations.CreateModel(
            name='FollowUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('session_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
