# Generated by Django 4.2.7 on 2026-03-06

from django.db import migrations, models
import django.db.models.deletion


def migrate_and_seed_data(apps, schema_editor):
    TipoAvaliacao = apps.get_model("forms", "TipoAvaliacao")
    Avaliacao = apps.get_model("forms", "Avaliacao")
    TipoProcedimento = apps.get_model("forms", "TipoProcedimento")
    Procedimento = apps.get_model("forms", "Procedimento")
    Sessao = apps.get_model("forms", "Sessao")

    tipos_avaliacao = {
        "Anamnese": TipoAvaliacao.objects.get_or_create(nome="Anamnese")[0],
        "Anamnese Acupuntura": TipoAvaliacao.objects.get_or_create(nome="Anamnese Acupuntura")[0],
        "Anamnese Pilates": TipoAvaliacao.objects.get_or_create(nome="Anamnese Pilates")[0],
        "Avaliação Drenagem": TipoAvaliacao.objects.get_or_create(nome="Avaliação Drenagem")[0],
    }

    for nome in ["Fisioterapia", "Acupuntura", "Drenagem Linfática", "Pilates"]:
        TipoProcedimento.objects.get_or_create(nome=nome)

    # Evita conflito para constraint de unicidade em nomes de tipo de procedimento.
    nomes_vistos = set()
    for tipo in TipoProcedimento.objects.all().order_by("id"):
        nome_base = (tipo.nome or "Tipo sem nome").strip() or "Tipo sem nome"
        nome_final = nome_base
        while nome_final.lower() in nomes_vistos:
            nome_final = f"{nome_base} ({tipo.id})"
        if nome_final != tipo.nome:
            tipo.nome = nome_final
            tipo.save(update_fields=["nome"])
        nomes_vistos.add(nome_final.lower())

    status_map = {
        "scheduled": "agendada",
        "completed": "realizada",
        "cancelled": "cancelada",
        "missed": "faltou",
        "agendada": "agendada",
        "realizada": "realizada",
        "cancelada": "cancelada",
        "faltou": "faltou",
    }

    for sessao in Sessao.objects.all().iterator():
        novo_status = status_map.get(sessao.status, "agendada")
        if getattr(sessao, "completed", False):
            novo_status = "realizada"
        sessao.status = novo_status
        sessao.save(update_fields=["status"])

    # Converte procedimentos com perfil de anamnese em avaliações únicas.
    nomes_para_avaliacao = {
        "anamnese": "Anamnese",
        "anamnese geral": "Anamnese",
        "anamnese acupuntura": "Anamnese Acupuntura",
        "anamnese pilates": "Anamnese Pilates",
        "avaliação drenagem": "Avaliação Drenagem",
    }

    ids_para_remover = []
    for procedimento in Procedimento.objects.select_related("tipo_procedimento", "paciente").all().iterator():
        tipo_nome = (procedimento.tipo_procedimento.nome or "").strip().lower()
        alvo = nomes_para_avaliacao.get(tipo_nome)
        if not alvo:
            continue

        primeira_sessao = (
            Sessao.objects.filter(procedimento_id=procedimento.pk)
            .order_by("data_hora")
            .first()
        )
        data_hora = primeira_sessao.data_hora if primeira_sessao else procedimento.created_at

        Avaliacao.objects.create(
            paciente_id=procedimento.paciente_id,
            tipo_avaliacao_id=tipos_avaliacao[alvo].pk,
            data_hora=data_hora,
            concluida=procedimento.concluido,
            observacoes=procedimento.observacoes,
            created_at=procedimento.created_at,
            updated_at=procedimento.updated_at,
        )
        ids_para_remover.append(procedimento.pk)

    if ids_para_remover:
        Sessao.objects.filter(procedimento_id__in=ids_para_remover).delete()
        Procedimento.objects.filter(pk__in=ids_para_remover).delete()


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0013_proceduresession_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FichaInscricao",
            new_name="Paciente",
        ),
        migrations.RenameModel(
            old_name="ProcedureType",
            new_name="TipoProcedimento",
        ),
        migrations.RenameModel(
            old_name="Procedure",
            new_name="Procedimento",
        ),
        migrations.RenameModel(
            old_name="ProcedureSession",
            new_name="Sessao",
        ),
        migrations.RenameField(
            model_name="tipoprocedimento",
            old_name="name",
            new_name="nome",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="patient",
            new_name="paciente",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="procedure_type",
            new_name="tipo_procedimento",
        ),
        migrations.RenameField(
            model_name="procedimento",
            old_name="is_complete",
            new_name="concluido",
        ),
        migrations.RenameField(
            model_name="sessao",
            old_name="procedure",
            new_name="procedimento",
        ),
        migrations.RenameField(
            model_name="sessao",
            old_name="scheduled_datetime",
            new_name="data_hora",
        ),
        migrations.RenameField(
            model_name="sessao",
            old_name="notes",
            new_name="observacoes",
        ),
        migrations.CreateModel(
            name="TipoAvaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Avaliação",
                "verbose_name_plural": "Tipos de Avaliação",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_hora", models.DateTimeField()),
                ("concluida", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="avaliacoes", to="forms.paciente"),
                ),
                (
                    "tipo_avaliacao",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="avaliacoes", to="forms.tipoavaliacao"),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.AddField(
            model_name="sessao",
            name="assinatura_confirmada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sessao",
            name="numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="paciente",
            options={"ordering": ["-created_at"], "verbose_name": "Paciente", "verbose_name_plural": "Pacientes"},
        ),
        migrations.AlterModelOptions(
            name="tipoprocedimento",
            options={"ordering": ["nome"], "verbose_name": "Tipo de Procedimento", "verbose_name_plural": "Tipos de Procedimento"},
        ),
        migrations.AlterModelOptions(
            name="procedimento",
            options={"ordering": ["-created_at"], "verbose_name": "Procedimento", "verbose_name_plural": "Procedimentos"},
        ),
        migrations.AlterModelOptions(
            name="sessao",
            options={"ordering": ["data_hora"], "verbose_name": "Sessão", "verbose_name_plural": "Sessões"},
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="paciente",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="procedimentos", to="forms.paciente"),
        ),
        migrations.AlterField(
            model_name="procedimento",
            name="tipo_procedimento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="procedimentos", to="forms.tipoprocedimento"),
        ),
        migrations.AlterField(
            model_name="sessao",
            name="procedimento",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sessoes", to="forms.procedimento"),
        ),
        migrations.RunPython(migrate_and_seed_data, noop_reverse),
        migrations.AlterField(
            model_name="tipoprocedimento",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name="sessao",
            name="completed",
        ),
        migrations.AlterField(
            model_name="sessao",
            name="status",
            field=models.CharField(
                choices=[("agendada", "Agendada"), ("realizada", "Realizada"), ("faltou", "Faltou"), ("cancelada", "Cancelada")],
                default="agendada",
                max_length=20,
            ),
        ),
    ]
