# Generated by Django 4.2.7 on 2026-05-25 13:52

from django.db import migrations, models
import django.db.models.manager

from core.migration_operations import CreateModelIfNotExists


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CreateModelIfNotExists(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('profissao', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('telefone_comercial', models.CharField(blank=True, max_length=15)),
                ('data_nascimento', models.DateField()),
                ('data_matricula', models.DateField()),
                ('plano', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'forms_paciente',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
