# Generated by Django 4.2.7 on 2026-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager

from core.migration_operations import AddFieldIfMissing, CreateModelIfNotExists


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('concluido', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'db_table': 'forms_procedimento',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='TipoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('habilita_exercicios', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Procedimento',
                'verbose_name_plural': 'Tipos de Procedimento',
                'db_table': 'forms_tipoprocedimento',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('data_hora', models.DateTimeField()),
                ('duracao_minutos', models.PositiveIntegerField(default=60)),
                ('numero', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('faltou', 'Faltou'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('assinatura_confirmada', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'db_table': 'forms_sessao',
                'ordering': ['data_hora'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        AddFieldIfMissing(
            model_name='procedimento',
            name='tipo_procedimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimentos', to='procedimentos.tipoprocedimento'),
        ),
    ]
