# Generated by Django 4.2.7 on 2026-03-02 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_anamneseacupuntura_paciente_anamnesegeral_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichainscricao',
            name='profissao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='anamneseacupuntura',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_acupuntura', to='forms.fichainscricao', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='anamnesegeral',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anamneses_geral', to='forms.fichainscricao', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='fichadrenagem',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_drenagem', to='forms.fichainscricao', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='fichaexercicios',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fichas_exercicios', to='forms.fichainscricao', verbose_name='Paciente'),
        ),
    ]
