# Generated by Django 4.2.7 on 2026-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_fichainscricao_profissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anamneseacupuntura',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anamnesegeral',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichadrenagem',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fichaexercicios',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
