# Generated by Django 4.2.7 on 2026-03-06 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_anamnesegeral_dor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.fichainscricao')),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='forms.procedure')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='procedure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.proceduretype'),
        ),
    ]
