# Generated by Django 4.2.7 on 2026-03-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_remove_legacy_procedure_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedure',
            options={'ordering': ['-created_at'], 'verbose_name': 'Procedimento', 'verbose_name_plural': 'Procedimentos'},
        ),
        migrations.AlterModelOptions(
            name='proceduresession',
            options={'ordering': ['scheduled_datetime'], 'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
        migrations.AlterModelOptions(
            name='proceduretype',
            options={'verbose_name': 'Tipo de Procedimento', 'verbose_name_plural': 'Tipos de Procedimento'},
        ),
        migrations.AlterField(
            model_name='procedure',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='forms.fichainscricao'),
        ),
    ]
