# Generated by Django 4.2.7 on 2026-03-06 18:57

from django.db import migrations, models


def set_status_from_completed(apps, schema_editor):
    ProcedureSession = apps.get_model("forms", "ProcedureSession")
    ProcedureSession.objects.filter(completed=True).update(status="completed")


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_alter_procedure_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('missed', 'Faltou')], default='scheduled', max_length=20),
        ),
        migrations.RunPython(set_status_from_completed, noop_reverse),
    ]
