# Generated by Django 4.2.7 on 2026-03-06 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_avaliacao_paciente_procedimento_sessao_tipoavaliacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_exercicios', to='forms.paciente')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_exercicios', to='forms.procedimento')),
            ],
            options={
                'verbose_name': 'Ficha de Exercícios',
                'verbose_name_plural': 'Fichas de Exercícios',
                'ordering': ['-created_at'],
            },
        ),
    ]
