# Generated by Django 4.2.7 on 2026-03-13 17:37

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0017_alter_avaliacao_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tipoprocedimento',
            name='habilita_exercicios',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProcedimentoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimento_exercicios', to='forms.exerciciocatalogo')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimento_exercicios', to='forms.procedimento')),
            ],
            options={
                'verbose_name': 'Exercício do Procedimento',
                'verbose_name_plural': 'Exercícios do Procedimento',
                'ordering': ['ordem', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='procedimentoexercicio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('procedimento', 'exercicio'), name='unique_active_exercicio_por_procedimento'),
        ),
    ]
