# Generated by Django 4.2.7 on 2026-03-13 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


def migrate_legacy_procedure_exercises_to_sessions(apps, schema_editor):
    ProcedimentoExercicio = apps.get_model("forms", "ProcedimentoExercicio")
    Sessao = apps.get_model("forms", "Sessao")
    SessaoExercicio = apps.get_model("forms", "SessaoExercicio")

    active_session_statuses = {"agendada", "realizada"}
    existing_pairs = set(
        SessaoExercicio.all_objects.filter(is_active=True).values_list("sessao_id", "exercicio_id")
    )

    procedure_exercises = (
        ProcedimentoExercicio.all_objects.filter(is_active=True)
        .select_related("procedimento", "exercicio")
        .order_by("procedimento_id", "ordem", "created_at", "pk")
    )

    for procedure_exercise in procedure_exercises.iterator():
        sessions = (
            Sessao.all_objects.filter(
                procedimento_id=procedure_exercise.procedimento_id,
                is_active=True,
                status__in=active_session_statuses,
            )
            .order_by("data_hora", "numero", "pk")
        )
        for sessao in sessions.iterator():
            pair = (sessao.pk, procedure_exercise.exercicio_id)
            if pair in existing_pairs:
                continue
            SessaoExercicio.objects.create(
                sessao_id=sessao.pk,
                exercicio_id=procedure_exercise.exercicio_id,
                ordem=procedure_exercise.ordem,
                series=procedure_exercise.series,
                repeticoes=procedure_exercise.repeticoes,
                frequencia=procedure_exercise.frequencia,
                progressao=procedure_exercise.progressao,
                observacoes=procedure_exercise.observacoes,
                status=procedure_exercise.status,
                assigned_at=procedure_exercise.created_at,
            )
            existing_pairs.add(pair)


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_categoriaexercicio_exerciciocatalogo_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciciocatalogo',
            name='max_sessoes_consecutivas',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='exerciciocatalogo',
            name='sessoes_ate_cooldown',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='SessaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessao_exercicios', to='forms.exerciciocatalogo')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_exercicios', to='forms.sessao')),
            ],
            options={
                'verbose_name': 'Exercício da Sessão',
                'verbose_name_plural': 'Exercícios da Sessão',
                'ordering': ['ordem', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='sessaoexercicio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sessao', 'exercicio'), name='unique_active_exercicio_por_sessao'),
        ),
        migrations.RunPython(migrate_legacy_procedure_exercises_to_sessions, migrations.RunPython.noop),
    ]
