# Generated by Django 4.2.7 on 2026-03-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0020_exerciciocatalogo_max_sessoes_consecutivas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
