# Generated by Django 4.2.7 on 2026-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone

from core.migration_operations import AddConstraintIfNotExists, CreateModelIfNotExists


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procedimentos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        CreateModelIfNotExists(
            name='CategoriaExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoria de Exercício',
                'verbose_name_plural': 'Categorias de Exercícios',
                'db_table': 'forms_categoriaexercicio',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='ExercicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('instrucoes', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('max_sessoes_consecutivas', models.PositiveIntegerField(default=2)),
                ('sessoes_ate_cooldown', models.PositiveIntegerField(default=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicios', to='exercicios.categoriaexercicio')),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'db_table': 'forms_exerciciocatalogo',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='SessaoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessao_exercicios', to='exercicios.exerciciocatalogo')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessao_exercicios', to='procedimentos.sessao')),
            ],
            options={
                'verbose_name': 'Exercício da Sessão',
                'verbose_name_plural': 'Exercícios da Sessão',
                'db_table': 'forms_sessaoexercicio',
                'ordering': ['ordem', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='ProcedimentoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('repeticoes', models.CharField(blank=True, max_length=50)),
                ('frequencia', models.CharField(blank=True, max_length=100)),
                ('progressao', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedimento_exercicios', to='exercicios.exerciciocatalogo')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimento_exercicios', to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Exercício do Procedimento',
                'verbose_name_plural': 'Exercícios do Procedimento',
                'db_table': 'forms_procedimentoexercicio',
                'ordering': ['ordem', 'created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        CreateModelIfNotExists(
            name='FichaExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_exercicios', to='pacientes.paciente')),
                ('procedimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_exercicios', to='procedimentos.procedimento')),
            ],
            options={
                'verbose_name': 'Ficha de Exercícios',
                'verbose_name_plural': 'Fichas de Exercícios',
                'db_table': 'forms_fichaexercicios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        AddConstraintIfNotExists(
            model_name='sessaoexercicio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('sessao', 'exercicio'), name='unique_active_exercicio_por_sessao'),
        ),
        AddConstraintIfNotExists(
            model_name='procedimentoexercicio',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('procedimento', 'exercicio'), name='unique_active_exercicio_por_procedimento'),
        ),
    ]
