# Generated by Django 4.2.7 on 2026-07-13 23:27

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciciocatalogo',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='exerciciocatalogo',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), models.F('categoria'), condition=models.Q(('is_active', True)), name='unique_active_exercicio_por_categoria_nome'),
        ),
    ]
