# Generated by Codex on 2026-08-13

from django.core.validators import RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercicios", "0002_alter_exerciciocatalogo_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriaexercicio",
            name="cor",
            field=models.CharField(
                blank=True,
                default="",
                max_length=7,
                validators=[
                    RegexValidator(
                        regex=r"^#[0-9A-Fa-f]{6}$",
                        message="Informe uma cor hexadecimal no formato #RRGGBB.",
                    )
                ],
            ),
        ),
    ]
